modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="coosanta_metal_pipe"
version="1.0.0"
displayName="Metal Pipes and Other Stuff etc etc"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="hhowe, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.coosanta_metal_pipe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration