modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="coosanta_metal_pipe"
version="1.0.0"
displayName="Metal Pipes and Other Stuff etc etc"
displayURL="https://github.com/Coosanta17/Metal-Pipe"
logoFile="logo.png"
credits="I couldn't be bothered to code this myself so I used MCreator - https://mcreator.net/"
authors="Coosanta"
description="adds Metal Pipes"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.coosanta_metal_pipe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration